version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./Client/my-mini-project # Path to frontend directory
  #     dockerfile: Dockerfile
  #   image: my-frontend
  #   ports:
  #     - "4000:80" # Expose frontend on port 4000
  #   networks:
  #     - my-network

  # server:
  #   build:
  #     context: ./Server # Path to backend directory
  #     dockerfile: Dockerfile
  #   image: my-server
  #   ports:
  #     - "5001:5000" # Expose backend on port 5001
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200 # Elasticsearch link on updated port
  #   networks:
  #     - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elk123
      - xpack.security.enabled=false # Disable security for easier setup (optional)
    ports:
      - "9200:9200" # Remap Elasticsearch to avoid conflict with host port 9200
    networks:
      - my-network

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.9.0
  #   volumes:
  #     - ./ELK/logstash.conf:/usr/share/logstash/pipeline/logstash.conf # Mount the logstash.conf file
  #   environment:
  #     - LS_JAVA_OPTS=-Xms512m -Xmx512m # JVM heap size for Logstash
  #   ports:
  #     - "5044:5044" # Input from Filebeat
  #     # - "9601:9600" # Expose Logstash monitoring port
  #   depends_on:
  #     - elasticsearch # Ensure Logstash starts after Elasticsearch
  #   networks:
  #     - my-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    volumes:
      - ./ELK/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./ELK/logs/dummy:/usr/share/filebeat/logs/dummy
    depends_on:
      - elasticsearch # Ensure Filebeat starts after Logstash
    networks:
      - my-network

  nginx:
    build:
      context: ./NetFlix/ # Path to Netflix clone directory
      dockerfile: Dockerfile
    container_name: netflix_clone
    ports:
      - "80:80" # Expose NGINX on port 80
    volumes:
      - ./NetFlix/nginx.conf:/etc/nginx/nginx.conf # Mount your custom NGINX config
      - ./NetFlix/logs:/var/log/nginx # Mount host directory for logs
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 6MB

networks:
  my-network:
    driver: bridge
