version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # Store data persistently for testing
      - ./mysql_logs:/var/log/mysql # Store MySQL logs for error checking
      - ./init_db:/docker-entrypoint-initdb.d # Run initial scripts to populate data
